version: '2.3'
services:
  test-cpu-base:
    build:
      context: .
      dockerfile: Dockerfile.test.cpu
      args:
        UBUNTU_VERSION: 18.04
        GPP_VERSION: 7
        MPI_KIND: None
        PYTHON_VERSION: 3.8
        TENSORFLOW_PACKAGE: tensorflow-cpu==2.4.1
        KERAS_PACKAGE: keras==2.4.3
        PYTORCH_PACKAGE: torch==1.7.1+cpu
        TORCHVISION_PACKAGE: torchvision==0.8.2+cpu
        MXNET_PACKAGE: mxnet==1.7.0b20200813
        PYSPARK_PACKAGE: pyspark==3.0.1
        SPARK_PACKAGE: spark-3.0.1/spark-3.0.1-bin-hadoop2.7.tgz
        HOROVOD_BUILD_FLAGS: HOROVOD_WITH_GLOO=1
    privileged: true
    shm_size: 8gb

  test-cpu-gloo-py3_8-tf2_4_1-keras2_4_3-torch1_7_1-mxnet1_4_0-pyspark_3_0_1:
    extends: test-cpu-base
    build:
      args:
        MXNET_PACKAGE: mxnet==1.4.0
  test-cpu-gloo-py3_8-tf2_4_1-keras2_4_3-torch1_7_1-mxnet1_4_0_p0-pyspark_3_0_1:
    extends: test-cpu-base
    build:
      args:
        MXNET_PACKAGE: mxnet==1.4.0.post0
  test-cpu-gloo-py3_8-tf2_4_1-keras2_4_3-torch1_7_1-mxnet1_4_1-pyspark_3_0_1:
    extends: test-cpu-base
    build:
      args:
        MXNET_PACKAGE: mxnet==1.4.1
  test-cpu-gloo-py3_8-tf2_4_1-keras2_4_3-torch1_7_1-mxnet1_5_0-pyspark_3_0_1:
    extends: test-cpu-base
    build:
      args:
        MXNET_PACKAGE: mxnet==1.5.0
  test-cpu-gloo-py3_8-tf2_4_1-keras2_4_3-torch1_7_1-mxnet1_5_1-pyspark_3_0_1:
    extends: test-cpu-base
    build:
      args:
        MXNET_PACKAGE: mxnet==1.5.1
  test-cpu-gloo-py3_8-tf2_4_1-keras2_4_3-torch1_7_1-mxnet1_5_1_p0-pyspark_3_0_1:
    extends: test-cpu-base
    build:
      args:
        MXNET_PACKAGE: mxnet==1.5.1.post0
  test-cpu-gloo-py3_8-tf2_4_1-keras2_4_3-torch1_7_1-mxnet1_6_0-pyspark_3_0_1:
    extends: test-cpu-base
    build:
      args:
        MXNET_PACKAGE: mxnet==1.6.0
  test-cpu-gloo-py3_8-tf2_4_1-keras2_4_3-torch1_7_1-mxnet1_7_0_p1-pyspark_3_0_1:
    extends: test-cpu-base
    build:
      args:
        MXNET_PACKAGE: mxnet==1.7.0.post1

  test-gpu-base:
    build:
      context: .
      dockerfile: Dockerfile.test.gpu
      args:
        CUDA_DOCKER_VERSION: 10.1-devel-ubuntu18.04
        CUDNN_VERSION: 7.6.5.32-1+cuda10.1
        NCCL_VERSION_OVERRIDE: 2.7.8-1+cuda10.1
        GPP_VERSION: 7
        MPI_KIND: None
        PYTHON_VERSION: 3.8
        TENSORFLOW_PACKAGE: tensorflow-gpu==2.3.2
        KERAS_PACKAGE: keras==2.3.1
        PYTORCH_PACKAGE: torch==1.6.0+cu101
        TORCHVISION_PACKAGE: torchvision==0.7.0+cu101
        # mxnet-cu101==1.7.0.post1 does not exist, mxnet-cu101==1.7.0 does but misses mkldnn headers
        # https://github.com/apache/incubator-mxnet/issues/19575
        # mxnet-cu101==1.7.0.post1 is not yet released, but this serves as an RC:
        # https://repo.mxnet.io/dist/python/cu101/mxnet_cu101-1.7.0b20200813-py2.py3-none-manylinux2014_x86_64.whl
        MXNET_PACKAGE: mxnet-cu110==1.7.0b20200813
        PYSPARK_PACKAGE: pyspark==3.0.1
        SPARK_PACKAGE: spark-3.0.1/spark-3.0.1-bin-hadoop2.7.tgz
        HOROVOD_BUILD_FLAGS: HOROVOD_GPU_OPERATIONS=NCCL
        HOROVOD_MIXED_INSTALL: 0
    runtime: nvidia
    # We plumb CUDA_VISIBLE_DEVICES instead of NVIDIA_VISIBLE_DEVICES because
    # the latter does not work in privileged mode that we use in the containers.
    environment:
      - CUDA_VISIBLE_DEVICES
    privileged: true
    shm_size: 8gb

  test-gpu-gloo-py3_7-tf1_15_5-keras2_2_4-torch1_3_1-mxnet1_4_0-pyspark_3_0_1:
    extends: test-gpu-base
    build:
      args:
        CUDA_DOCKER_VERSION: 10.0-devel-ubuntu18.04
        PYTHON_VERSION: 3.7
        TENSORFLOW_PACKAGE: tensorflow-gpu==1.15.5
        KERAS_PACKAGE: keras==2.2.4
        PYTORCH_PACKAGE: torch==1.3.1+cu100
        TORCHVISION_PACKAGE: torchvision==0.4.2+cu100
        MXNET_PACKAGE: mxnet-cu100==1.4.0
  test-gpu-gloo-py3_7-tf1_15_5-keras2_2_4-torch1_3_1-mxnet1_4_0_p0-pyspark_3_0_1:
    extends: test-gpu-base
    build:
      args:
        CUDA_DOCKER_VERSION: 10.0-devel-ubuntu18.04
        PYTHON_VERSION: 3.7
        TENSORFLOW_PACKAGE: tensorflow-gpu==1.15.5
        KERAS_PACKAGE: keras==2.2.4
        PYTORCH_PACKAGE: torch==1.3.1+cu100
        TORCHVISION_PACKAGE: torchvision==0.4.2+cu100
        MXNET_PACKAGE: mxnet-cu100==1.4.0.post0
  test-gpu-gloo-py3_7-tf1_15_5-keras2_2_4-torch1_3_1-mxnet1_4_1-pyspark_3_0_1:
    extends: test-gpu-base
    build:
      args:
        CUDA_DOCKER_VERSION: 10.0-devel-ubuntu18.04
        PYTHON_VERSION: 3.7
        TENSORFLOW_PACKAGE: tensorflow-gpu==1.15.5
        KERAS_PACKAGE: keras==2.2.4
        PYTORCH_PACKAGE: torch==1.3.1+cu100
        TORCHVISION_PACKAGE: torchvision==0.4.2+cu100
        MXNET_PACKAGE: mxnet-cu100==1.4.1
  test-gpu-gloo-py3_7-tf1_15_5-keras2_2_4-torch1_3_1-mxnet1_5_0-pyspark_3_0_1:
    extends: test-gpu-base
    build:
      args:
        CUDA_DOCKER_VERSION: 10.0-devel-ubuntu18.04
        PYTHON_VERSION: 3.7
        TENSORFLOW_PACKAGE: tensorflow-gpu==1.15.5
        KERAS_PACKAGE: keras==2.2.4
        PYTORCH_PACKAGE: torch==1.3.1+cu100
        TORCHVISION_PACKAGE: torchvision==0.4.2+cu100
        MXNET_PACKAGE: mxnet-cu100==1.5.0
  test-gpu-gloo-py3_7-tf1_15_5-keras2_2_4-torch1_3_1-mxnet1_5_1-pyspark_3_0_1:
    extends: test-gpu-base
    build:
      args:
        CUDA_DOCKER_VERSION: 10.0-devel-ubuntu18.04
        PYTHON_VERSION: 3.7
        TENSORFLOW_PACKAGE: tensorflow-gpu==1.15.5
        KERAS_PACKAGE: keras==2.2.4
        PYTORCH_PACKAGE: torch==1.3.1+cu100
        TORCHVISION_PACKAGE: torchvision==0.4.2+cu100
        MXNET_PACKAGE: mxnet-cu100==1.5.1
  test-gpu-gloo-py3_7-tf1_15_5-keras2_2_4-torch1_3_1-mxnet1_5_1_p0-pyspark_3_0_1:
    extends: test-gpu-base
    build:
      args:
        CUDA_DOCKER_VERSION: 10.0-devel-ubuntu18.04
        PYTHON_VERSION: 3.7
        TENSORFLOW_PACKAGE: tensorflow-gpu==1.15.5
        KERAS_PACKAGE: keras==2.2.4
        PYTORCH_PACKAGE: torch==1.3.1+cu100
        TORCHVISION_PACKAGE: torchvision==0.4.2+cu100
        MXNET_PACKAGE: mxnet-cu100==1.5.1.post0
  test-gpu-gloo-py3_7-tf1_15_5-keras2_2_4-torch1_3_1-mxnet1_7_0-pyspark_3_0_1:
    extends: test-gpu-base
    build:
      args:
        CUDA_DOCKER_VERSION: 10.0-devel-ubuntu18.04
        PYTHON_VERSION: 3.7
        TENSORFLOW_PACKAGE: tensorflow-gpu==1.15.5
        KERAS_PACKAGE: keras==2.2.4
        PYTORCH_PACKAGE: torch==1.3.1+cu100
        TORCHVISION_PACKAGE: torchvision==0.4.2+cu100
        MXNET_PACKAGE: mxnet-cu100==1.7.0

  test-gpu-gloo-py3_8-tf2_3_2-keras2_3_1-torch1_6_0-mxnet1_4_1-pyspark_3_0_1:
    extends: test-gpu-base
    build:
      args:
        TENSORFLOW_PACKAGE: tensorflow-gpu==2.3.2
        KERAS_PACKAGE: keras==2.3.1
        PYTORCH_PACKAGE: torch==1.6.0+cu101
        TORCHVISION_PACKAGE: torchvision==0.7.0+cu101
        MXNET_PACKAGE: mxnet-cu101==1.4.1
  test-gpu-gloo-py3_8-tf2_3_2-keras2_3_1-torch1_6_0-mxnet1_5_0-pyspark_3_0_1:
    extends: test-gpu-base
    build:
      args:
        TENSORFLOW_PACKAGE: tensorflow-gpu==2.3.2
        KERAS_PACKAGE: keras==2.3.1
        PYTORCH_PACKAGE: torch==1.6.0+cu101
        TORCHVISION_PACKAGE: torchvision==0.7.0+cu101
        MXNET_PACKAGE: mxnet-cu101==1.5.0
  test-gpu-gloo-py3_8-tf2_3_2-keras2_3_1-torch1_6_0-mxnet1_5_1-pyspark_3_0_1:
    extends: test-gpu-base
    build:
      args:
        TENSORFLOW_PACKAGE: tensorflow-gpu==2.3.2
        KERAS_PACKAGE: keras==2.3.1
        PYTORCH_PACKAGE: torch==1.6.0+cu101
        TORCHVISION_PACKAGE: torchvision==0.7.0+cu101
        MXNET_PACKAGE: mxnet-cu101==1.5.1
  test-gpu-gloo-py3_8-tf2_3_2-keras2_3_1-torch1_6_0-mxnet1_5_1_p0-pyspark_3_0_1:
    extends: test-gpu-base
    build:
      args:
        TENSORFLOW_PACKAGE: tensorflow-gpu==2.3.2
        KERAS_PACKAGE: keras==2.3.1
        PYTORCH_PACKAGE: torch==1.6.0+cu101
        TORCHVISION_PACKAGE: torchvision==0.7.0+cu101
        MXNET_PACKAGE: mxnet-cu101==1.5.1.post0
  test-gpu-gloo-py3_8-tf2_3_2-keras2_3_1-torch1_6_0-mxnet1_6_0_p0-pyspark_3_0_1:
    extends: test-gpu-base
    build:
      args:
        TENSORFLOW_PACKAGE: tensorflow-gpu==2.3.2
        KERAS_PACKAGE: keras==2.3.1
        PYTORCH_PACKAGE: torch==1.6.0+cu101
        TORCHVISION_PACKAGE: torchvision==0.7.0+cu101
        MXNET_PACKAGE: mxnet-cu101==1.6.0.post0
  test-gpu-gloo-py3_8-tf2_3_2-keras2_3_1-torch1_6_0-mxnet1_7_0-pyspark_3_0_1:
    extends: test-gpu-base
    build:
      args:
        TENSORFLOW_PACKAGE: tensorflow-gpu==2.3.2
        KERAS_PACKAGE: keras==2.3.1
        PYTORCH_PACKAGE: torch==1.6.0+cu101
        TORCHVISION_PACKAGE: torchvision==0.7.0+cu101
        MXNET_PACKAGE: mxnet-cu101==1.7.0

